Contact front end
redcraft-org/redcraft_website pull request #26
Opened 2020-11-08 23:13 UTC by Likyaz

2020-11-08 23:44 UTC, Cod3lta requested changes

2020-11-08 23:44 UTC, Cod3lta commented on website/service/DiscordService.py
> +            # url='https://discord.com/api/webhooks/thisIsAFakeWebhook',
Remove this comment

2020-11-08 23:44 UTC, Cod3lta commented on website/static/website/js/pages/contact.js
> +            // document.querySelector("#contact-form").submit()
Remove this comment

2020-11-08 23:58 UTC, lululombard requested changes
Small changes

2020-11-08 23:58 UTC, lululombard commented on .env.example
> +URL_WEBHOOK_CONTACT_DISCORD = 'https://yourWebhookUrl'
Maybe give a bit more guidance by setting the URL by setting it to `https://discordapp.com/api/webhooks/insert_channel_id_here/insert_token_here`

```suggestion
URL_WEBHOOK_CONTACT_DISCORD = 'https://discordapp.com/api/webhooks/insert_channel_id_here/insert_token_here'
```

2020-11-08 23:58 UTC, lululombard commented on website/views.py
> +        # ip = self.request.headers["cf-connecting-ip"]
```suggestion
        ip = self.request.headers.get('CF-Connecting-IP', self.request.META.get('REMOTE_ADDR'))
```

2020-11-08 23:58 UTC, lululombard commented on website/views.py
> +        ip = "0.0.0.0"
Remove that line and use the one above

2020-11-08 23:58 UTC, lululombard commented on website/views.py
> +            valide_email = re.match(r'^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$', email)
Why not use the built in Django validator? https://docs.djangoproject.com/en/3.1/ref/validators/#emailvalidator

2020-11-08 23:58 UTC, lululombard commented on website/views.py
> +                list_err += ['minecraft nickname is not valide']
```suggestion
                list_err += ['Minecraft username is not valid']
```

2020-11-08 23:58 UTC, lululombard commented on website/views.py
> +        if minecraft_nickname:
I'd prefer this variable to be named `minecraft_username`, because the nickname could be the ingame /nick command and be confusing

2020-11-09 22:39 UTC, lululombard approved these changes

2020-11-09 23:19 UTC, Cod3lta approved these changes

2020-11-09 23:22 UTC, merged